// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkgfshkrnqnjzlgalweg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrZ2ZzaGtybnFuanpsZ2Fsd2VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1MTE0ODMsImV4cCI6MjA1MjA4NzQ4M30.rfGAvWDlJ8qHKpYGUzpT2OF4V_o9U2As3nhNCGVuB-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);